### ISSUE TITLE
Error adding dependency

### ISSUE THREAD

**Issue by AugustoMarcelo** [GuilhE/android-circular-progress-view#1]
When adding the view as a dependency, errors are generated in other dependencies like app compat

**Comment by GuilhE** [comment]
Never had a problem with that, though you can exclude Android dependencies using this:
```
compile ('com.github.guilhe:circular-progress-view:${LATEST_VERSION}'){
    exclude group: 'com.android.support', module: 'appcompat-v7'
}
```

But you still have to use an appcompat dependency (another version in your case I guess) without it, it won't work.

Can you post your gradle configuration?

**Comment by AugustoMarcelo** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'
    defaultConfig {
        applicationId "br.com.ufrn.marceloaugusto.minhazoraslight"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}
repositories {
    mavenLocal()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.0-alpha1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha8'
    compile 'com.github.eralpyucel:CircleProgressView:v1.1'
    compile 'com.jaredrummler:material-spinner:1.1.0'
    compile 'com.github.guilhe:circular-progress-view:${LATEST_VERSION}'
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:design:26.0.0-alpha1'
}

**Comment by GuilhE** [comment]
Change `26.0.0-alpha1` to `26.0.1` and if it doesn't help, show the output error please.

**Comment by AugustoMarcelo** [comment]
Yes, I'm using 1.0.0. The error persist
```
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:E:/ProjetosAndroid/MinhazorasLight/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

Error:Failed to resolve: com.android.support:support-annotations:26.0.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:E:/ProjetosAndroid/MinhazorasLight/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>
```

**Comment by GuilhE** [comment]
Check if you have this in your **project** `build.gradle`:
```
allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}
```

**Comment by AugustoMarcelo** [comment]
Sorry for the delay. I included the snippet of code you showed and it worked.
