### ISSUE TITLE
bar thickness isn't changing

### ISSUE THREAD

**Issue by n8glenn** [GuilhE/android-circular-progress-view#12]
Hi,

I love this control, it's very nicely done and easy to use, but I do have a strange problem.  I want the bar thickness to expand so that it's essentially a circle with a shrinking cutout.  I tried adjusting the progress bar thickness both in the layout file and in the activity itself, but it has no effect.  This is strange, because I tested the sample project and the thickness can be changed through the UI.  Am I doing something wrong or is this a bug?  Thanks,,

Nate

**Comment by GuilhE** [comment]
Hello Nate,

Can you please provide some code samples so we can hopefully pin point the problem?
Thanks.

**Comment by n8glenn** [comment]
sure,  here is the layout:

                    <com.github.guilhe.circularprogressview.CircularProgressView
                        android:id="@+id/hostUpProgress"
                        android:layout_height="match_parent"
                        android:layout_width="match_parent"
                        app:progress="55"
                        app:progressBarThickness="50dp"
                        app:progressBarColor="@color/green"
                        android:layout_marginTop="5dp"
                        android:layout_marginRight="8dp"
                        android:layout_marginBottom="0dp"
                        />


and the code in my activity:

                hostUpProgress.setReverseEnabled(false);
                hostUpProgress.setVisibility(View.VISIBLE);
                hostUpProgress.setProgressStrokeThickness(30.0f); // this doesn't seem to be having an effect
                ObjectAnimator progressAnimator = ObjectAnimator.ofFloat(hostUpProgress, "progress", 0, 100);
                progressAnimator.setDuration(1000 * FPS);
                progressAnimator.setInterpolator(new LinearInterpolator());
                progressAnimator.start();

**Comment by GuilhE** [comment]
I'm changing by code and it works:
`setProgressStrokeThickness(30.0f);`
![30](https://user-images.githubusercontent.com/2677139/46180624-5bd19400-c2b9-11e8-8876-486e90e879b8.png)
`setProgressStrokeThickness(60.0f);`
![60](https://user-images.githubusercontent.com/2677139/46180632-6a1fb000-c2b9-11e8-9eb3-ff22d10b6a19.png)
`setProgressStrokeThickness(90.0f);`
![90](https://user-images.githubusercontent.com/2677139/46180639-6ee46400-c2b9-11e8-9b5b-dcbd81b39597.png)



Regarding this:
```
            ObjectAnimator progressAnimator = ObjectAnimator.ofFloat(hostUpProgress, "progress", 0, 100);
            progressAnimator.setDuration(1000 * FPS);
            progressAnimator.setInterpolator(new LinearInterpolator());
            progressAnimator.start();
```

You can use this methods to achieve the same:
```
public void setAnimationInterpolator(TimeInterpolator interpolator)
public void setProgress(float progress, boolean animate, long duration)
```

Regards.

**Comment by n8glenn** [comment]
Changing the thickness works for me when I use a value from 1 to 10.  If I set the value higher than 10, there is no change in the appearance of the control.  I did implement the code you provided to do animations and it does work as expected, but again, the bar thickness isn't getting larger than 10dp.

**Comment by GuilhE** [comment]
https://github.com/GuilhE/android-circular-progress-view/blob/682d2fb2498ca3daf167b24047cd96455db555be/circular-progress-view/src/main/java/com/github/guilhe/circularprogressview/CircularProgressView.java#L492-L493

I've this condition in the `onMeasure` method. Is this condition valid in your layout?

**Comment by GuilhE** [comment]
Any news?

**Comment by GuilhE** [comment]
@n8glenn you didn't provide more feedback can I close this "issue"?

**Comment by n8glenn** [comment]
I think this may be caused by the way the control is added to the layout file.  I used "match_parent" instead of setting a size explicitly, this might be the reason, otherwise I have no idea why it is happening.
