### ISSUE TITLE
Can the ends of the progress bar be round?

### ISSUE THREAD

**Issue by imyyq-star** [GuilhE/android-circular-progress-view#13]
Can the ends of the progress bar be round?
![image](https://user-images.githubusercontent.com/11580876/53789083-91f8fb00-3f5e-11e9-9b03-3689d1ab6c59.png)

**Comment by GuilhE** [comment]
Hello,
At the moment isn't possible, but feel free to contribute :)

Thanks.

**Comment by GuilhE** [comment]
Now available in v1.3.3
