### ISSUE TITLE
ERROR: Failed to resolve: com.github.guilhe:circular-progress-view:${LATEST_VERSION}

### ISSUE THREAD

**Issue by zgao67** [GuilhE/android-circular-progress-view#16]
Trying to install it in my build.gradle 
    implementation 'com.github.guilhe:circular-progress-view:${LATEST_VERSION}'
but showed the error. 
please help to fix thanks a lot

**Comment by GuilhE** [comment]
Have you tried `implementation 'com.github.guilhe:circular-progress-view:1.4.0'`?

**Comment by zgao67** [comment]
I did 
and it gave me an error message as well 

INFO: One of the plugins you are using supports Java 8 language features. To try the support built into the Android plugin, remove the following from your build.gradle:
    apply plugin: 'me.tatarka.retrolambda'
To learn more, go to https://d.android.com/r/tools/java-8-support-message.html
Affected Modules: app

**Comment by zgao67** [comment]
I tired to add the java 8 language features by following this link, it does not see to work as well 
https://stackoverflow.com/questions/43423057/how-to-enable-java-8-language-features-in-android-studio

**Comment by GuilhE** [comment]
Have you tried this: https://developer.android.com/studio/write/java8-support?utm_source=android-studio#migrate_from_retrolambda?

**Comment by zgao67** [comment]
That works 
thanks a log :)
