### ISSUE TITLE
Background color is manipulated. It should not be.

### ISSUE THREAD

**Issue by burakozhan** [GuilhE/android-circular-progress-view#5]
if in the XML `app:progressBarColor` and `app:backgroundColor` are set to the same color I expect that the resulting circle is always full. Currently whatever is set as background color is reduced so it looks dim. 

I have a usecase where the background needs to progress. (so the progressbar has a dim color and the remainder has a bright color) As the library is forcefully dimming the background color, I cannot realize my "bright color for remainder" design. 

In this linked line you you set an Alpha value to the background color. This should be optional, not mandatory.
[CircularProgressView.java Line 126](https://github.com/GuilhE/android-circular-progress-view/blob/b67d30ce9d78230188bb186bb2f15ad19421c1f7/circular-progress-view/src/main/java/com/github/guilhe/circularprogressview/CircularProgressView.java#L126)

**Comment by GuilhE** [comment]
Hello Burak,

Let me see if I understand your problem. You want to disable the background alpha, but if you do that you won't, visually, distinguish the progress %. 
In your use-case are you using a progress thumb and you want a "wheel" effect like this:

![sample](https://user-images.githubusercontent.com/2677139/36859731-31e06e9c-1d77-11e8-88ae-be864ece3237.png)

Is that it?

**Comment by burakozhan** [comment]
Hi, 
let me show you what I am trying to accomplish. Currently I accomplish that by changing the starting Angle, but to be honest, that is not very practical. 
![progressbar](https://user-images.githubusercontent.com/7325233/36893385-2884753c-1e08-11e8-825a-9ae9ab0ec119.png)

So, if there was the possibility to avoid the Alpha value you forcefully set on the background color, then I could simply swap the colors with what I need. 
I have tried to manipuate the DEFAULT_BACKGROUND_ALPHA to be 1.0f by Reflection, but that seems a bit crazy for such a simple thing. So it would be nice if you could include a flag so that the background color I apply is set completely, not Alpha changed. 
If you want I can implement it and send you a pull request.

**Comment by GuilhE** [comment]
Hi,
Ok I got it ;)
I'll add **setters** to control alpha's value (background and shadow), instead of a boolean, it gives you more control in the end. What do you think?

**Comment by GuilhE** [comment]
Merged 👍 
I'll be pushing it to maven tonight ;)

**Comment by burakozhan** [comment]
Wow! That was fast. Thanks! :+1:

**Comment by GuilhE** [comment]
It's out [v1.2.2](https://search.maven.org/#artifactdetails%7Ccom.github.guilhe%7Ccircular-progress-view%7C1.2.2%7Caar) 💯
