### ISSUE TITLE
Multiple arcs on one progress [ENHANCEMENT]

### ISSUE THREAD

**Issue by Akshshr** [GuilhE/android-circular-progress-view#8]
Is there a way to make different arcs of different colors with each having an "progress"? Max being 360

For example 
Cats 100
Dogs 200
Fish 60

Would be cool!

**Comment by GuilhE** [comment]
Hello,
At the moment it's not possible and I don't have much time on my hands. As soon as I can I'll look into it. It's a cool features for sure.
Meanwhile, feel free to contribute.

Thanks.

**Comment by GuilhE** [comment]
Good news, feature almost finished! ;)
Just some minor details that need to be polished and it will be released.

Cheers.

**Comment by GuilhE** [comment]
Feature done, just have to wait for maven now.
In this first version no animation is available.

**Comment by GuilhE** [comment]
@Akshshr it's out [v1.3.0](https://search.maven.org/#artifactdetails%7Ccom.github.guilhe%7Ccircular-progress-view%7C1.3.0%7Caar)
